# Generated by Django 4.1.7 on 2023-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testing",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="testing",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
